version: "3"

services:
  app:
    build: .
    container_name: go_graphql
    volumes:
      - .:/go/src/
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: proxy-reverso
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge