version: "3.9"

networks: 
  appteste-network:
    driver: bridge

services:
  database_postgres:
    image: postgres
    container_name: appteste_postgres
    ports:
    - "5432:5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=appteste
    volumes:
      - pgdata:/data/postgres
    networks:
      - appteste-network
  app:
    build: .
    container_name: appteste
    restart: always
    ports:
    - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - appteste-network
    depends_on:
      - database_postgres

volumes:
  pgdata:
    driver: local